"""token version for revocation

Revision ID: 0002_token_version
Revises: 0001_initial
Create Date: 2026-09-30 09:00:31.515837
"""
from alembic import op
import sqlalchemy as sa


revision = '0002_token_version'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_version', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch:
        batch.drop_column('token_version')
    # ### end Alembic commands ###
