"""per-workspace work item numbering

Work item numbers were a single global sequence shared by every workspace. They are now unique per
workspace and allocated from a locked per-workspace counter. Existing numbers are kept; each counter
starts after the highest number already used in that workspace and year.

Downgrade restores the global unique index and fails if two workspaces have since reused a number.

Revision ID: 0003_workspace_numbering
Revises: 0002_token_version
Create Date: 2026-09-30 09:10:49.082191
"""
from alembic import op
import uuid

import sqlalchemy as sa


revision = '0003_workspace_numbering'
down_revision = '0002_token_version'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_item_counters',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'year')
    )
    highest = {}
    for workspace_id, number in op.get_bind().execute(sa.text("SELECT workspace_id, work_item_number FROM work_items")):
        parts = (number or "").split("-")
        if len(parts) == 3 and parts[1].isdigit() and parts[2].isdigit():
            key = (uuid.UUID(str(workspace_id)), int(parts[1]))
            highest[key] = max(highest.get(key, 0), int(parts[2]))
    if highest:
        counters = sa.table("work_item_counters", sa.column("workspace_id", sa.Uuid()), sa.column("year", sa.Integer()), sa.column("last_value", sa.Integer()))
        op.bulk_insert(counters, [{"workspace_id": w, "year": y, "last_value": v} for (w, y), v in highest.items()])
    op.drop_index(op.f('ix_work_items_work_item_number'), table_name='work_items')
    op.create_index(op.f('ix_work_items_work_item_number'), 'work_items', ['work_item_number'], unique=False)
    op.create_index('ix_work_items_workspace_number', 'work_items', ['workspace_id', 'work_item_number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_work_items_workspace_number', table_name='work_items')
    op.drop_index(op.f('ix_work_items_work_item_number'), table_name='work_items')
    op.create_index(op.f('ix_work_items_work_item_number'), 'work_items', ['work_item_number'], unique=True)
    op.drop_table('work_item_counters')
    # ### end Alembic commands ###
